version: "3.9"

volumes:
  db_data: {}

services:
  example:
    build: .
    restart: on-failure

    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: my_user
      POSTGRES_DB: my_db
      POSTGRES_PASSWORD: mysecretpassword

    volumes:
      - db_data:/var/lib/postgres/data


